# Generated by Django 5.0.3 on 2024-03-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijoz',
            name='qarz',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
