# Generated by Django 5.0.3 on 2024-03-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_tarqatuvchi_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarqatuvchi',
            name='qarz',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
